### ISSUE TITLE
Mehr Textinhalt!

### ISSUE THREAD

**Issue by lemoer** [freifunkh/fnorden.net#13]
Wir sollten mehr Textinhalte präsentieren. Ich öffne hier mal den Thread zur Diskussion darüber.

Hier was ich mir bisher aus den Fingern gesaugt habe:

----

Wir sind ein gemeinnütziger Förderverein, der Projekte rund um freie Netzwerke
unterstützt, fördert und voranbringt. Wir verfolgen hauptsächlich einen Bildungs- und
Aufklärungsauftrag. Zu unserem Engagement gehören:

- Vorträge über die Relevanz und Ideen freier Netzwerke
- Politisches Engagement
- Technische Schulungen, wie man freie Netzwerke aufbaut

Wir unterstützen unter anderem Freifunk Hannover.

[LOGO von Freifunk Hannover]

**Comment by lemoer** [comment]
Ne, ich denke, das was wir aktuell auf der Startseite haben, genügt. Aber wenn wir das Issue noch 2 Jahre offen lassen, dann können wir sein 10-Jähriges Jubiläum feiern...

**Comment by AiyionPrime** [comment]
:clown_face:

**Comment by lemoer** [comment]
Naja, 8 Jahre (auf den Tag genau) ist ja auch schon ein bisschen....
