### ISSUE TITLE
Datum in der Satzung korrigieren

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/fnorden.net#17]
@1977er hat neulich ein Datum eingetragen, bittet aber um Korrektur.
(Im commit cba35e83b27c757b119b66010db8f90409f5a46f)

@cawi2001 wenn du da die Tage zu kommst, wäre das prima.

**Comment by AiyionPrime** [comment]
Das könnte daran liegen, dass paypal die immernoch ausgibt:

https://www.paypal.com/donate/buttons

**Comment by 1977er** [comment]
Ist das noch ein offenes Todo?

**Comment by AiyionPrime** [comment]
Ah, i hoped my reply would end up here; it did not. So here goes nothing:

> Ja.
Die Antwort auf das regelmäßige Pieksen lautet "Das müsste ich in den
Unterlagen nachsehen." direkt nach dem Hinweis, "das steht doch auf
unserer Website".

**Comment by 1977er** [comment]
Wir brauchen eh eine neue Satzung (bzw eine Änderung) in naher Zukunft. Bis dahin würde ich dieses Issue ignorieren.

**Comment by AiyionPrime** [comment]
...

**Comment by AiyionPrime** [comment]
@cawi2001 sagte gerade er würde das nochmal nachgucken

**Comment by AiyionPrime** [comment]
@cawi2001 hat gerade eine beglaubigte Abschrift durchgesehen, aus der das Datum hervorgeht; danke dafür.
@1977er zitiert das Länderportal mit dem 21. September 19

**Comment by 1977er** [comment]
Ich zitierte das Länderportal mit dem 21.9.2015.

**Comment by AiyionPrime** [comment]
Aye
